### PR TITLE
Added prettier to lint files

### PR DESCRIPTION
**Pull request by Nautman**
This makes for a standardized formatting, which I highly recommend.

### CODE REVIEW

**Comment by charlesmaddock** [comment]
Hmm, the syntax has been changed in many files, will this result in merge conflicts? Otherwise I definitely think we should have this!

**Comment by Nautman** [comment]
The syntax has basically been prettified in all files. You are correct in that this will likely cause some merge conflicts, but they will be very easy to solve. To fix them, all you have to do is simply choose the newest code, and ignore the prettified changes.

Once you commit, these files will be prettified again.

**Comment by charlesmaddock** [comment]
I think it would be easier to add lint files without the commit c5c7d63 that prettifies everything. I'm creating a separate branch for that and closing this one.

**Comment by Nautman** [comment]
OK, you could just revert the last commit without creating a new branch.

**Comment by charlesmaddock** [comment]
Good point. I'll fix the conflicts and merge this

**Comment by charlesmaddock** [comment]
Thanks hehe

**Pull request merged**
